title: The Language Applications Grid
description: An open framework for interoperable NLP web services
markdown: kramdown
#branch: gh-pages
theme: jekyll-theme-cayman
top: "<a class='top' href='#top'>Back to top</a>"
redcarpet:
    extensions: [fenced_code_blocks, no_intra_emphasis, tables, autolink]
